export const SAVE_DATA = 'SAVE_DATA';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_DEPARTURES = 'UPDATE_DEPARTURES';
export const SET_INTERVAL_ID = 'SET_INTERVAL_ID';
export const ADD_POLLING_RESULTS = "ADD_POLLING_RESULTS";